
alpha: 2.  # alpha-divergence param
use_kl_loss: false # additional KL loss.
w_adjust_clip: 10.
smc:
  use_resampling: false
  n_intermediate_distributions: 10
  spacing_type: linear
  transition_operator: hmc # [hmc or metropolis]
  hmc:
    n_outer_steps: 1
    n_inner_steps: 5
    init_step_size: 1e-2
    target_p_accept: 0.65
    tune_step_size: true
  metropolis:
    n_outer_steps: 1
    init_step_size: 1.
    target_p_accept: 0.65 # Setting this lower can be good for exploration.
    tune_step_size: true # If false, then init_step_size needs to be reasonably good.
  point_is_valid_fn:
    type: default # [default, in_bounds]
    in_bounds:
      min: -100
      max: 100
buffer:
  with_buffer: True
  buffer_max_length_in_batches: 400
  buffer_min_length_in_batches: 40
  n_updates_per_smc_forward_pass: 4