defaults:
  - fab: default
  - flow: default
  - training: default
  - hydra: default
  - _self_

flow:
  n_layers: 4
  transform_type: spline # spline or real_nvp
  conditioner_mlp_units: [128, 128]
  spline_max:  16. # If using spline then it helps to have bounds to roughly match problem.
  spline_min: -16.
  act_norm: false


fab:
  smc:
    transition_operator: hmc # [hmc or metropolis]
    n_intermediate_distributions: 4


training:
  # eval_batch_size: 20_000 # For reverse ESS calculation
  # n_samples_log_Z: 2_000 # eval_batch_size will be split into multiple batches of size n_samples_log_Z.
  n_epoch: 1000
  batch_size: 128


logger:
 list_logger: null
#  pandas_logger:
#    save_period: 1000 # how often to save the pandas dataframe as a csv
  # wandb:
  #   project: 4-mode
  #   job_type: FAB
  #   group: dim=2
